[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
dockerContext = "."

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
